package com.ihandy.quote_core.serverdb.dao;

import com.ihandy.quote_core.serverdb.model.TlCheXianSearchClaimInfo;

public interface TlCheXianSearchClaimInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long numClaimid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO
     *
     * @mbggenerated
     */
    int insert(TlCheXianSearchClaimInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO
     *
     * @mbggenerated
     */
    int insertSelective(TlCheXianSearchClaimInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO
     *
     * @mbggenerated
     */
    TlCheXianSearchClaimInfo selectByPrimaryKey(Long numClaimid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TlCheXianSearchClaimInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TlCheXianSearchClaimInfo record);
}