package com.ihandy.quote_core.serverdb.model;

import java.util.Date;

public class TlCheXianSearchCarInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    private Long numCarinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARUSEDTYPE
     *
     * @mbggenerated
     */
    private String vc2Carusedtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARVIN
     *
     * @mbggenerated
     */
    private String vc2Carvin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_MOLDNAME
     *
     * @mbggenerated
     */
    private String vc2Moldname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_ENGINENO
     *
     * @mbggenerated
     */
    private String vc2Engineno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSENO
     *
     * @mbggenerated
     */
    private String vc2Licenseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNER
     *
     * @mbggenerated
     */
    private String vc2Licenseowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_PURCHASEPRICE
     *
     * @mbggenerated
     */
    private Long numPurchaseprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARSEATED
     *
     * @mbggenerated
     */
    private Long numCarseated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_POSTEDNAME
     *
     * @mbggenerated
     */
    private String vc2Postedname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_INSUREDNAME
     *
     * @mbggenerated
     */
    private String vc2Insuredname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNERIDCARDNO
     *
     * @mbggenerated
     */
    private String vc2Licenseowneridcardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_LICENSEOWNERIDCARDTYPE
     *
     * @mbggenerated
     */
    private Long numLicenseowneridcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CITYCODEID
     *
     * @mbggenerated
     */
    private Long numCitycodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_COMPANYID
     *
     * @mbggenerated
     */
    private Long numCompanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_FORCEENDDATE
     *
     * @mbggenerated
     */
    private Object datForceenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_BIZENDDATE
     *
     * @mbggenerated
     */
    private Object datBizenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CARREGISTERDATE
     *
     * @mbggenerated
     */
    private Object datCarregisterdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    private Date datCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARINFOID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public Long getNumCarinfoid() {
        return numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARINFOID
     *
     * @param numCarinfoid the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public void setNumCarinfoid(Long numCarinfoid) {
        this.numCarinfoid = numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARUSEDTYPE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARUSEDTYPE
     *
     * @mbggenerated
     */
    public String getVc2Carusedtype() {
        return vc2Carusedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARUSEDTYPE
     *
     * @param vc2Carusedtype the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARUSEDTYPE
     *
     * @mbggenerated
     */
    public void setVc2Carusedtype(String vc2Carusedtype) {
        this.vc2Carusedtype = vc2Carusedtype == null ? null : vc2Carusedtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARVIN
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARVIN
     *
     * @mbggenerated
     */
    public String getVc2Carvin() {
        return vc2Carvin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARVIN
     *
     * @param vc2Carvin the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_CARVIN
     *
     * @mbggenerated
     */
    public void setVc2Carvin(String vc2Carvin) {
        this.vc2Carvin = vc2Carvin == null ? null : vc2Carvin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_MOLDNAME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_MOLDNAME
     *
     * @mbggenerated
     */
    public String getVc2Moldname() {
        return vc2Moldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_MOLDNAME
     *
     * @param vc2Moldname the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_MOLDNAME
     *
     * @mbggenerated
     */
    public void setVc2Moldname(String vc2Moldname) {
        this.vc2Moldname = vc2Moldname == null ? null : vc2Moldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_ENGINENO
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_ENGINENO
     *
     * @mbggenerated
     */
    public String getVc2Engineno() {
        return vc2Engineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_ENGINENO
     *
     * @param vc2Engineno the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_ENGINENO
     *
     * @mbggenerated
     */
    public void setVc2Engineno(String vc2Engineno) {
        this.vc2Engineno = vc2Engineno == null ? null : vc2Engineno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSENO
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSENO
     *
     * @mbggenerated
     */
    public String getVc2Licenseno() {
        return vc2Licenseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSENO
     *
     * @param vc2Licenseno the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSENO
     *
     * @mbggenerated
     */
    public void setVc2Licenseno(String vc2Licenseno) {
        this.vc2Licenseno = vc2Licenseno == null ? null : vc2Licenseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNER
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNER
     *
     * @mbggenerated
     */
    public String getVc2Licenseowner() {
        return vc2Licenseowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNER
     *
     * @param vc2Licenseowner the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNER
     *
     * @mbggenerated
     */
    public void setVc2Licenseowner(String vc2Licenseowner) {
        this.vc2Licenseowner = vc2Licenseowner == null ? null : vc2Licenseowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_PURCHASEPRICE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_PURCHASEPRICE
     *
     * @mbggenerated
     */
    public Long getNumPurchaseprice() {
        return numPurchaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_PURCHASEPRICE
     *
     * @param numPurchaseprice the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_PURCHASEPRICE
     *
     * @mbggenerated
     */
    public void setNumPurchaseprice(Long numPurchaseprice) {
        this.numPurchaseprice = numPurchaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARSEATED
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARSEATED
     *
     * @mbggenerated
     */
    public Long getNumCarseated() {
        return numCarseated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARSEATED
     *
     * @param numCarseated the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CARSEATED
     *
     * @mbggenerated
     */
    public void setNumCarseated(Long numCarseated) {
        this.numCarseated = numCarseated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_POSTEDNAME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_POSTEDNAME
     *
     * @mbggenerated
     */
    public String getVc2Postedname() {
        return vc2Postedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_POSTEDNAME
     *
     * @param vc2Postedname the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_POSTEDNAME
     *
     * @mbggenerated
     */
    public void setVc2Postedname(String vc2Postedname) {
        this.vc2Postedname = vc2Postedname == null ? null : vc2Postedname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_INSUREDNAME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_INSUREDNAME
     *
     * @mbggenerated
     */
    public String getVc2Insuredname() {
        return vc2Insuredname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_INSUREDNAME
     *
     * @param vc2Insuredname the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_INSUREDNAME
     *
     * @mbggenerated
     */
    public void setVc2Insuredname(String vc2Insuredname) {
        this.vc2Insuredname = vc2Insuredname == null ? null : vc2Insuredname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNERIDCARDNO
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNERIDCARDNO
     *
     * @mbggenerated
     */
    public String getVc2Licenseowneridcardno() {
        return vc2Licenseowneridcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNERIDCARDNO
     *
     * @param vc2Licenseowneridcardno the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.VC2_LICENSEOWNERIDCARDNO
     *
     * @mbggenerated
     */
    public void setVc2Licenseowneridcardno(String vc2Licenseowneridcardno) {
        this.vc2Licenseowneridcardno = vc2Licenseowneridcardno == null ? null : vc2Licenseowneridcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_LICENSEOWNERIDCARDTYPE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_LICENSEOWNERIDCARDTYPE
     *
     * @mbggenerated
     */
    public Long getNumLicenseowneridcardtype() {
        return numLicenseowneridcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_LICENSEOWNERIDCARDTYPE
     *
     * @param numLicenseowneridcardtype the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_LICENSEOWNERIDCARDTYPE
     *
     * @mbggenerated
     */
    public void setNumLicenseowneridcardtype(Long numLicenseowneridcardtype) {
        this.numLicenseowneridcardtype = numLicenseowneridcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CITYCODEID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CITYCODEID
     *
     * @mbggenerated
     */
    public Long getNumCitycodeid() {
        return numCitycodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CITYCODEID
     *
     * @param numCitycodeid the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_CITYCODEID
     *
     * @mbggenerated
     */
    public void setNumCitycodeid(Long numCitycodeid) {
        this.numCitycodeid = numCitycodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_COMPANYID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_COMPANYID
     *
     * @mbggenerated
     */
    public Long getNumCompanyid() {
        return numCompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_COMPANYID
     *
     * @param numCompanyid the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.NUM_COMPANYID
     *
     * @mbggenerated
     */
    public void setNumCompanyid(Long numCompanyid) {
        this.numCompanyid = numCompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_FORCEENDDATE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_FORCEENDDATE
     *
     * @mbggenerated
     */
    public Object getDatForceenddate() {
        return datForceenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_FORCEENDDATE
     *
     * @param datForceenddate the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_FORCEENDDATE
     *
     * @mbggenerated
     */
    public void setDatForceenddate(Object datForceenddate) {
        this.datForceenddate = datForceenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_BIZENDDATE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_BIZENDDATE
     *
     * @mbggenerated
     */
    public Object getDatBizenddate() {
        return datBizenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_BIZENDDATE
     *
     * @param datBizenddate the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_BIZENDDATE
     *
     * @mbggenerated
     */
    public void setDatBizenddate(Object datBizenddate) {
        this.datBizenddate = datBizenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CARREGISTERDATE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CARREGISTERDATE
     *
     * @mbggenerated
     */
    public Object getDatCarregisterdate() {
        return datCarregisterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CARREGISTERDATE
     *
     * @param datCarregisterdate the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CARREGISTERDATE
     *
     * @mbggenerated
     */
    public void setDatCarregisterdate(Object datCarregisterdate) {
        this.datCarregisterdate = datCarregisterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CREATETIME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public Date getDatCreatetime() {
        return datCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CREATETIME
     *
     * @param datCreatetime the value for QCYB.TL_CHEXIAN_SEARCH_CARINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public void setDatCreatetime(Date datCreatetime) {
        this.datCreatetime = datCreatetime;
    }
}