package com.ihandy.quote_core.serverdb.model;

import java.math.BigDecimal;
import java.util.Date;

public class TlCheXianSearchQuoteInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_QUOTEID
     *
     * @mbggenerated
     */
    private Long numQuoteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    private Long numCarinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHESUN
     *
     * @mbggenerated
     */
    private Long numChesun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SANZHE
     *
     * @mbggenerated
     */
    private Long numSanzhe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_DAOQIANG
     *
     * @mbggenerated
     */
    private Long numDaoqiang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SIJI
     *
     * @mbggenerated
     */
    private Long numSiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHENGKE
     *
     * @mbggenerated
     */
    private Long numChengke;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BOLI
     *
     * @mbggenerated
     */
    private Long numBoli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_HUAHEN
     *
     * @mbggenerated
     */
    private Long numHuahen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANCHESUN
     *
     * @mbggenerated
     */
    private Long numBujimianchesun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANSANZHE
     *
     * @mbggenerated
     */
    private Long numBujimiansanzhe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANRENYUAN
     *
     * @mbggenerated
     */
    private Long numBujimianrenyuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANDAOQIANG
     *
     * @mbggenerated
     */
    private Long numBujimiandaoqiang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANFUJIA
     *
     * @mbggenerated
     */
    private Long numBujimianfujia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SHESHUI
     *
     * @mbggenerated
     */
    private BigDecimal numSheshui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHEDENG
     *
     * @mbggenerated
     */
    private BigDecimal numChedeng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_ZIRAN
     *
     * @mbggenerated
     */
    private BigDecimal numZiran;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    private Date datCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_QUOTEID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_QUOTEID
     *
     * @mbggenerated
     */
    public Long getNumQuoteid() {
        return numQuoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_QUOTEID
     *
     * @param numQuoteid the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_QUOTEID
     *
     * @mbggenerated
     */
    public void setNumQuoteid(Long numQuoteid) {
        this.numQuoteid = numQuoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CARINFOID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public Long getNumCarinfoid() {
        return numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CARINFOID
     *
     * @param numCarinfoid the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public void setNumCarinfoid(Long numCarinfoid) {
        this.numCarinfoid = numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHESUN
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHESUN
     *
     * @mbggenerated
     */
    public Long getNumChesun() {
        return numChesun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHESUN
     *
     * @param numChesun the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHESUN
     *
     * @mbggenerated
     */
    public void setNumChesun(Long numChesun) {
        this.numChesun = numChesun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SANZHE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SANZHE
     *
     * @mbggenerated
     */
    public Long getNumSanzhe() {
        return numSanzhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SANZHE
     *
     * @param numSanzhe the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SANZHE
     *
     * @mbggenerated
     */
    public void setNumSanzhe(Long numSanzhe) {
        this.numSanzhe = numSanzhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_DAOQIANG
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_DAOQIANG
     *
     * @mbggenerated
     */
    public Long getNumDaoqiang() {
        return numDaoqiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_DAOQIANG
     *
     * @param numDaoqiang the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_DAOQIANG
     *
     * @mbggenerated
     */
    public void setNumDaoqiang(Long numDaoqiang) {
        this.numDaoqiang = numDaoqiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SIJI
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SIJI
     *
     * @mbggenerated
     */
    public Long getNumSiji() {
        return numSiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SIJI
     *
     * @param numSiji the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SIJI
     *
     * @mbggenerated
     */
    public void setNumSiji(Long numSiji) {
        this.numSiji = numSiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHENGKE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHENGKE
     *
     * @mbggenerated
     */
    public Long getNumChengke() {
        return numChengke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHENGKE
     *
     * @param numChengke the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHENGKE
     *
     * @mbggenerated
     */
    public void setNumChengke(Long numChengke) {
        this.numChengke = numChengke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BOLI
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BOLI
     *
     * @mbggenerated
     */
    public Long getNumBoli() {
        return numBoli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BOLI
     *
     * @param numBoli the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BOLI
     *
     * @mbggenerated
     */
    public void setNumBoli(Long numBoli) {
        this.numBoli = numBoli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_HUAHEN
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_HUAHEN
     *
     * @mbggenerated
     */
    public Long getNumHuahen() {
        return numHuahen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_HUAHEN
     *
     * @param numHuahen the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_HUAHEN
     *
     * @mbggenerated
     */
    public void setNumHuahen(Long numHuahen) {
        this.numHuahen = numHuahen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANCHESUN
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANCHESUN
     *
     * @mbggenerated
     */
    public Long getNumBujimianchesun() {
        return numBujimianchesun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANCHESUN
     *
     * @param numBujimianchesun the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANCHESUN
     *
     * @mbggenerated
     */
    public void setNumBujimianchesun(Long numBujimianchesun) {
        this.numBujimianchesun = numBujimianchesun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANSANZHE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANSANZHE
     *
     * @mbggenerated
     */
    public Long getNumBujimiansanzhe() {
        return numBujimiansanzhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANSANZHE
     *
     * @param numBujimiansanzhe the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANSANZHE
     *
     * @mbggenerated
     */
    public void setNumBujimiansanzhe(Long numBujimiansanzhe) {
        this.numBujimiansanzhe = numBujimiansanzhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANRENYUAN
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANRENYUAN
     *
     * @mbggenerated
     */
    public Long getNumBujimianrenyuan() {
        return numBujimianrenyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANRENYUAN
     *
     * @param numBujimianrenyuan the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANRENYUAN
     *
     * @mbggenerated
     */
    public void setNumBujimianrenyuan(Long numBujimianrenyuan) {
        this.numBujimianrenyuan = numBujimianrenyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANDAOQIANG
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANDAOQIANG
     *
     * @mbggenerated
     */
    public Long getNumBujimiandaoqiang() {
        return numBujimiandaoqiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANDAOQIANG
     *
     * @param numBujimiandaoqiang the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANDAOQIANG
     *
     * @mbggenerated
     */
    public void setNumBujimiandaoqiang(Long numBujimiandaoqiang) {
        this.numBujimiandaoqiang = numBujimiandaoqiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANFUJIA
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANFUJIA
     *
     * @mbggenerated
     */
    public Long getNumBujimianfujia() {
        return numBujimianfujia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANFUJIA
     *
     * @param numBujimianfujia the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_BUJIMIANFUJIA
     *
     * @mbggenerated
     */
    public void setNumBujimianfujia(Long numBujimianfujia) {
        this.numBujimianfujia = numBujimianfujia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SHESHUI
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SHESHUI
     *
     * @mbggenerated
     */
    public BigDecimal getNumSheshui() {
        return numSheshui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SHESHUI
     *
     * @param numSheshui the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_SHESHUI
     *
     * @mbggenerated
     */
    public void setNumSheshui(BigDecimal numSheshui) {
        this.numSheshui = numSheshui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHEDENG
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHEDENG
     *
     * @mbggenerated
     */
    public BigDecimal getNumChedeng() {
        return numChedeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHEDENG
     *
     * @param numChedeng the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_CHEDENG
     *
     * @mbggenerated
     */
    public void setNumChedeng(BigDecimal numChedeng) {
        this.numChedeng = numChedeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_ZIRAN
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_ZIRAN
     *
     * @mbggenerated
     */
    public BigDecimal getNumZiran() {
        return numZiran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_ZIRAN
     *
     * @param numZiran the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.NUM_ZIRAN
     *
     * @mbggenerated
     */
    public void setNumZiran(BigDecimal numZiran) {
        this.numZiran = numZiran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.DAT_CREATETIME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public Date getDatCreatetime() {
        return datCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.DAT_CREATETIME
     *
     * @param datCreatetime the value for QCYB.TL_CHEXIAN_SEARCH_QUOTEINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public void setDatCreatetime(Date datCreatetime) {
        this.datCreatetime = datCreatetime;
    }
}