package com.ihandy.quote_core.serverdb.model;

import java.util.Date;

public class TlCheXianSearchPeopleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_PEOPLEID
     *
     * @mbggenerated
     */
    private Long numPeopleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ROLE
     *
     * @mbggenerated
     */
    private String vc2Role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TYPE
     *
     * @mbggenerated
     */
    private String vc2Type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_NAME
     *
     * @mbggenerated
     */
    private String vc2Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_COMPANYPRO
     *
     * @mbggenerated
     */
    private String vc2Companypro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_IDCARDNO
     *
     * @mbggenerated
     */
    private String vc2Idcardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_IDTYPE
     *
     * @mbggenerated
     */
    private Long numIdtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ADDRESS
     *
     * @mbggenerated
     */
    private String vc2Address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_EMAIL
     *
     * @mbggenerated
     */
    private String vc2Email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TELNUM
     *
     * @mbggenerated
     */
    private String vc2Telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_MOBILENUM
     *
     * @mbggenerated
     */
    private String vc2Mobilenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    private Long numCarinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    private Date datCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_PEOPLEID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_PEOPLEID
     *
     * @mbggenerated
     */
    public Long getNumPeopleid() {
        return numPeopleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_PEOPLEID
     *
     * @param numPeopleid the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_PEOPLEID
     *
     * @mbggenerated
     */
    public void setNumPeopleid(Long numPeopleid) {
        this.numPeopleid = numPeopleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ROLE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ROLE
     *
     * @mbggenerated
     */
    public String getVc2Role() {
        return vc2Role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ROLE
     *
     * @param vc2Role the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ROLE
     *
     * @mbggenerated
     */
    public void setVc2Role(String vc2Role) {
        this.vc2Role = vc2Role == null ? null : vc2Role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TYPE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TYPE
     *
     * @mbggenerated
     */
    public String getVc2Type() {
        return vc2Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TYPE
     *
     * @param vc2Type the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TYPE
     *
     * @mbggenerated
     */
    public void setVc2Type(String vc2Type) {
        this.vc2Type = vc2Type == null ? null : vc2Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_NAME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_NAME
     *
     * @mbggenerated
     */
    public String getVc2Name() {
        return vc2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_NAME
     *
     * @param vc2Name the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_NAME
     *
     * @mbggenerated
     */
    public void setVc2Name(String vc2Name) {
        this.vc2Name = vc2Name == null ? null : vc2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_COMPANYPRO
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_COMPANYPRO
     *
     * @mbggenerated
     */
    public String getVc2Companypro() {
        return vc2Companypro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_COMPANYPRO
     *
     * @param vc2Companypro the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_COMPANYPRO
     *
     * @mbggenerated
     */
    public void setVc2Companypro(String vc2Companypro) {
        this.vc2Companypro = vc2Companypro == null ? null : vc2Companypro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_IDCARDNO
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_IDCARDNO
     *
     * @mbggenerated
     */
    public String getVc2Idcardno() {
        return vc2Idcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_IDCARDNO
     *
     * @param vc2Idcardno the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_IDCARDNO
     *
     * @mbggenerated
     */
    public void setVc2Idcardno(String vc2Idcardno) {
        this.vc2Idcardno = vc2Idcardno == null ? null : vc2Idcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_IDTYPE
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_IDTYPE
     *
     * @mbggenerated
     */
    public Long getNumIdtype() {
        return numIdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_IDTYPE
     *
     * @param numIdtype the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_IDTYPE
     *
     * @mbggenerated
     */
    public void setNumIdtype(Long numIdtype) {
        this.numIdtype = numIdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ADDRESS
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ADDRESS
     *
     * @mbggenerated
     */
    public String getVc2Address() {
        return vc2Address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ADDRESS
     *
     * @param vc2Address the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_ADDRESS
     *
     * @mbggenerated
     */
    public void setVc2Address(String vc2Address) {
        this.vc2Address = vc2Address == null ? null : vc2Address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_EMAIL
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_EMAIL
     *
     * @mbggenerated
     */
    public String getVc2Email() {
        return vc2Email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_EMAIL
     *
     * @param vc2Email the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_EMAIL
     *
     * @mbggenerated
     */
    public void setVc2Email(String vc2Email) {
        this.vc2Email = vc2Email == null ? null : vc2Email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TELNUM
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TELNUM
     *
     * @mbggenerated
     */
    public String getVc2Telnum() {
        return vc2Telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TELNUM
     *
     * @param vc2Telnum the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_TELNUM
     *
     * @mbggenerated
     */
    public void setVc2Telnum(String vc2Telnum) {
        this.vc2Telnum = vc2Telnum == null ? null : vc2Telnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_MOBILENUM
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_MOBILENUM
     *
     * @mbggenerated
     */
    public String getVc2Mobilenum() {
        return vc2Mobilenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_MOBILENUM
     *
     * @param vc2Mobilenum the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.VC2_MOBILENUM
     *
     * @mbggenerated
     */
    public void setVc2Mobilenum(String vc2Mobilenum) {
        this.vc2Mobilenum = vc2Mobilenum == null ? null : vc2Mobilenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_CARINFOID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public Long getNumCarinfoid() {
        return numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_CARINFOID
     *
     * @param numCarinfoid the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public void setNumCarinfoid(Long numCarinfoid) {
        this.numCarinfoid = numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.DAT_CREATETIME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public Date getDatCreatetime() {
        return datCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.DAT_CREATETIME
     *
     * @param datCreatetime the value for QCYB.TL_CHEXIAN_SEARCH_PEOPLEINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public void setDatCreatetime(Date datCreatetime) {
        this.datCreatetime = datCreatetime;
    }
}