package com.ihandy.quote_core.serverdb.model;

import java.util.Date;

public class TlCheXianSearchClaimInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CLAIMID
     *
     * @mbggenerated
     */
    private Long numClaimid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.VC2_PAYCOMPANYNAME
     *
     * @mbggenerated
     */
    private String vc2Paycompanyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYAMOUNT
     *
     * @mbggenerated
     */
    private Long numPayamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_ENDCASETIME
     *
     * @mbggenerated
     */
    private Object datEndcasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_LOSSTIME
     *
     * @mbggenerated
     */
    private Object datLosstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    private Long numCarinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    private Date datCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYCOMPANYID
     *
     * @mbggenerated
     */
    private Long numPaycompanyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CLAIMID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CLAIMID
     *
     * @mbggenerated
     */
    public Long getNumClaimid() {
        return numClaimid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CLAIMID
     *
     * @param numClaimid the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CLAIMID
     *
     * @mbggenerated
     */
    public void setNumClaimid(Long numClaimid) {
        this.numClaimid = numClaimid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.VC2_PAYCOMPANYNAME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.VC2_PAYCOMPANYNAME
     *
     * @mbggenerated
     */
    public String getVc2Paycompanyname() {
        return vc2Paycompanyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.VC2_PAYCOMPANYNAME
     *
     * @param vc2Paycompanyname the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.VC2_PAYCOMPANYNAME
     *
     * @mbggenerated
     */
    public void setVc2Paycompanyname(String vc2Paycompanyname) {
        this.vc2Paycompanyname = vc2Paycompanyname == null ? null : vc2Paycompanyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYAMOUNT
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYAMOUNT
     *
     * @mbggenerated
     */
    public Long getNumPayamount() {
        return numPayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYAMOUNT
     *
     * @param numPayamount the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYAMOUNT
     *
     * @mbggenerated
     */
    public void setNumPayamount(Long numPayamount) {
        this.numPayamount = numPayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_ENDCASETIME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_ENDCASETIME
     *
     * @mbggenerated
     */
    public Object getDatEndcasetime() {
        return datEndcasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_ENDCASETIME
     *
     * @param datEndcasetime the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_ENDCASETIME
     *
     * @mbggenerated
     */
    public void setDatEndcasetime(Object datEndcasetime) {
        this.datEndcasetime = datEndcasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_LOSSTIME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_LOSSTIME
     *
     * @mbggenerated
     */
    public Object getDatLosstime() {
        return datLosstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_LOSSTIME
     *
     * @param datLosstime the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_LOSSTIME
     *
     * @mbggenerated
     */
    public void setDatLosstime(Object datLosstime) {
        this.datLosstime = datLosstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CARINFOID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public Long getNumCarinfoid() {
        return numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CARINFOID
     *
     * @param numCarinfoid the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_CARINFOID
     *
     * @mbggenerated
     */
    public void setNumCarinfoid(Long numCarinfoid) {
        this.numCarinfoid = numCarinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_CREATETIME
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public Date getDatCreatetime() {
        return datCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_CREATETIME
     *
     * @param datCreatetime the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.DAT_CREATETIME
     *
     * @mbggenerated
     */
    public void setDatCreatetime(Date datCreatetime) {
        this.datCreatetime = datCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYCOMPANYID
     *
     * @return the value of QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYCOMPANYID
     *
     * @mbggenerated
     */
    public Long getNumPaycompanyid() {
        return numPaycompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYCOMPANYID
     *
     * @param numPaycompanyid the value for QCYB.TL_CHEXIAN_SEARCH_CLAIMINFO.NUM_PAYCOMPANYID
     *
     * @mbggenerated
     */
    public void setNumPaycompanyid(Long numPaycompanyid) {
        this.numPaycompanyid = numPaycompanyid;
    }
}